language: ruby
services:
  - postgresql
addons:
  chrome: stable
before_install:
  - nvm install node
before_script:
  - rm -rf spec/cassettes
script:
  - yarn add stimulus
  - bundle exec rake db:{create,migrate}
  - bundle exec rspec
