language: ruby
env:
  global:
    secure: C9d4+y7DAw8cTt5FKf6ZHbCK2GXViIludtQR2b0sH9C39k3HW/dOYRGCgofDttSANuKYO6FYK/OyKa90VOAYQUSDdiT74lZGCC0AFcD8s5h2nbFfLM1FB08roK5RNNbrO7YlVAzvx8FM/bgJGxiHtvEChhGc5ZAuYVTHlcH/bv1soQhUK5z+tCdUbb7Y68nXmPMcS1apd9w+xIfdzrJ158dUgml6eaFSXLXlsrq9aKiBwkzHn3AMdb2akwm2XNmw0Lexg0/mAu19B/Wg6ieTjPYJKyM60+qlmUpdytymeSb4e5dhE2y0gWoPY9LA43HzoWVpKn+78yafu1J+4XYsaiPFvR6eKFGbVWUlyXuh3FipBBY3GEECrzPVEur9EH+SQyGCZMO0ptO4VeSg4bZUdgkCGC2yec3mq1Oixgyrujjghdg6WOIEIzlOXU3GUEtiLusH3x1/ENlKIvIPay2MjlpbZbksDLoEmnzEoJoGTdxh4yonHzuTpzaQQCZhYcRGzGUWe27ifIsIy4JSRytMGgCeNJxh3PmnGPG/YbxL4RxD5yHCZcEQlF75wyVQ6MKTv/ciNInQOqlks6f8hrya/ArWJnR5BH2tO00UoXXzEHtYBMdRB2M7M4itiPAF0IuIZ95DEvmIMz278Ls2GEDcN0L8ZCbbgZLAOzdUB7Fj+zY=
services:
  - postgresql
before_script:
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
  - export CHROME_BIN=chromium-browser
script:
  - bundle exec rake db:{create,migrate,seed}
  - bundle exec rspec
